---
version: '3.3'
networks:
  play-metrics-net:
    driver: bridge

volumes:
  prometheus:
  grafana:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - play-metrics-net
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - play-metrics-net

  playmetrics:
    image: ppabis/google-play-report:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9300:9300
    volumes:
      - ./mykey.json:/app/mykey.json
    networks:
      - play-metrics-net
    depends_on:
      - prometheus